### PR TITLE
patch charset to include umlauts

### LINKED ISSUE #7: reprogram char map to contain German umlauts?
As per https://www.c64-wiki.de/index.php/Zeichen, this seems feasible.

We have plenty of messages which currently contain ae, oe, ue instead of the proper ä, ö, ü:

```
$ grep -r '[aou]e' src
src/itemz.c:	cprintf("\r\nn) Neu d) Loeschen s) Speichern m) Credit Modus q) Beenden\r\nr) Reset des Verkauft-Zaehlers\r\n");
src/itemz.c:		cprintf("\rEs ist bereits die maximale Anzahl an Eintraegen erreicht, druecke RETURN...\r\n");
src/itemz.c:	cprintf("\r Welcher Eintrag soll geloescht werden?\r\n");
src/itemz.c:				cprintf("Unbekannter Befehl, druecke RETURN...\r\n");
src/credit_manager.c:	cprintf("\r\nn) Neu d) Loeschen p) Einzahlen b) Seite hoch f) Seite runter\r\ng) Filtern e) Aendern s) Speichern z) Zurueck\r\n");
src/credit_manager.c:	cprintf("%d Cent eingezahlt fuer %s.\r\nRestguthaben: %d\r\n", deposit, credit->nickname, credit->credit);
src/credit_manager.c:	sprintf(print_buffer, "%c%s - %d Cent eingezahlt fuer %s. Restguthaben: %d Cent\r", 17, time, deposit, credit->nickname, credit->credit);
src/credit_manager.c:	cprintf("\r\nEinzahlung durchgefuehrt, druecke RETURN...\r\n");
src/credit_manager.c:		cprintf("\rEs ist bereits die maximale Anzahl an Eintraegen erreicht, druecke RETURN...\r\n");
src/credit_manager.c:	sprintf(print_buffer, "%c%s - Guthaben mit %d Cent fuer %s angelegt\r", 17, time, credit, name);
src/credit_manager.c:	cprintf("\r Welcher Eintrag soll geloescht werden?\r\n");
src/credit_manager.c:				cprintf("Unbekannter Befehl, druecke RETURN...\r\n");
src/kasse.c:			cprintf("Kauf abgebrochen, druecke RETURN...\r\n");
src/kasse.c:		cprintf("\r\nEinheit nicht in [-100, 100] oder 0, Abbruch, druecke RETURN...\r\n");
src/kasse.c:		cprintf(" fuer %s\r\n", nickname);
src/kasse.c:			cprintf("\r\nVerbleibendes Guthaben fuer %s: %s. Druecke RETURN...\r\n",
src/kasse.c:			cprintf("\r\nDein Guthaben betraegt noch %s.\r\n", rest);
src/kasse.c:			cprintf("\r\nNickname nicht gefunden in der Guthabenverwaltung! Abbruch, druecke RETURN...\r\n");
src/kasse.c:	cprintf("\r\nWie teuer ist \"%s\" (in cents)?\r\n", name);
src/kasse.c:			cprintf("Kauf abgebrochen, druecke RETURN...\r\n");
src/kasse.c:	cprintf("Gib die aktuelle Uhrzeit ein (Format HHMMSS):\r\n");
src/kasse.c:			cprintf("\r\nStatefile/Creditfile/Log gesichert, druecke RETURN...\r\n");
```

### PR DESCRIPTION
**Pull request by 9b17fe**
First stab to fix #7.
Still missing: a way to input umlauts.
IIRC there's a Kernal routine to map keycodes.

### CODE REVIEW

**Comment by stapelberg** [comment]
Before merging, can you please:

* run `make format` (I’ll need to set up a travis check for this)
* Rebase your changes to get rid of the merge commit? See `git rebase`

**Comment by 9b17fe** [comment]
rebased and reformatted.
I still want to doublecheck the order of the vdc 16bit register writes (and reads)
before merging.

**Comment by 9b17fe** [comment]
should be good to go!

**Comment by stapelberg** [comment]
Nice! @sur5r, did you want to test this on real hardware before merging?

**Pull request merged**
